### ISSUE TITLE
[Вопрос] Количество слоёв и узлов

### ISSUE THREAD

**Issue by freearhey** [Elco-/SimpleNN#1]
Хотел уточнить, чем именно ты руководствовался когда подбирал то или иное количество скрытых слоёв и узлов в них? Это случайный выбор, по результатам тестов или цифры взяты из какой-то статьи?

**Comment by ArtemOnigiri** [comment]
> Хотел уточнить, чем именно ты руководствовался когда подбирал то или иное количество скрытых слоёв и узлов в них? Это случайный выбор, по результатам тестов или цифры взяты из какой-то статьи?

Погуглил несколько статей, там везде разные значения, взял что-то среднее между ними😀

**Comment by freearhey** [comment]
Вот поэтому-то и решил спросить, так как обычно делаю тоже самое)

Единственное, пока изучал вопрос возникло ощущение что данная версия нейросети просто в принципе не может нормально справляться с изображениями. Ведь мы на вход ей подаём лишь список пикселей без какой-либо информации о их положении относительно друг друга. То есть достаточно немного сдвинуть линию на холсте и для сети это будет совершенно новый массив цифр и сколько бы мы не подготовили ей примеров этого всё рано будет недостаточно.

Так что видимо прийдется тебе в следующем видео уже ConvolutionNN описывать 😉
