### ISSUE TITLE
'dots' doesn't work as expected

### ISSUE THREAD

**Issue by stolario** [Elco-/SimpleNN#5]
Посмотрел видео, скачал исходники, запустил. Но нет, приложение не работает как на видео, не разграничивает области между точками. Примите меры )

**Comment by ArtemOnigiri** [comment]
Оно запускается? Форма появляется? Картинка как-то двигается? Пока не знаю, в чем может быть проблема

**Comment by stolario** [comment]
Запускается и на первый взгляд работает. Но области не разграничивает между точками...

**Comment by SSL0** [comment]
@stamanker Приложи скриншот, хотя бы. Как автор должен догадаться, в чем у тебя проблема?

**Comment by stolario** [comment]
![image](https://user-images.githubusercontent.com/13854302/78931143-1ac15f00-7aae-11ea-9daf-a2b529bae9f5.png)

**Comment by SSL0** [comment]
ЭМ, Ну так что ему разграничивать, зеленые точки, от зеленых? (Если что, синии кружки ставятся правой кнопкой мыши)

**Comment by stolario** [comment]
понятно )

**Comment by stolario** [comment]
И спасибо )
