### ISSUE TITLE
Алгоритм обратного распространения

### ISSUE THREAD

**Issue by SSL0** [Elco-/SimpleNN#8]
Хочу поинтересоваться, что за алгоритм ты используешь? Дело в том, что я нашел статью на хабре про нейронные сети и обратное распространение(https://habr.com/ru/post/313216/). Там используется немного другой поиск ошибки для нейронов скрытого слоя. А еще есть ролик на ютубе (https://www.youtube.com/watch?v=HA-F6cZPvrg), там еще один способ. И все из них, включая твой, отличаются, можешь сказать почему сделал именно так?

**Comment by ArtemOnigiri** [comment]
Скорее всего, способ один и тот же, просто у них выражено в более читабельном виде, в виде матриц. А у меня все в массивах, чтобы не плодить кучи объектов, оно ведь и так у меня выполняется на процессоре, что не быстро.
То есть, когда у них написано A * B
У меня это будет в виде 2 циклов с суммами произведений
